### ISSUE TITLE
【カードのアイコン】アイコンの画像が表示されない

### ISSUE THREAD

**Issue by unomitsu** [yamakenji24/CardCreator#10]
## バグ内容
githubとgoogleのアカウント両方、ブラウザ上でアイコンが表示されません。
saveはできますが、保存したカード画像のアイコン部分が真っ黒になっています。

## 実行環境
Windows10 64bit
Chrome 87.0.4280.88

## 再現手順
1. 「Sign in with github」「Sign in with google」のどちらかを押す
2. システムからのアクセスを許可する
3. 「save」を押してカードを保存する

## 期待される結果
ブラウザ上でアイコンが表示される。
保存したカードでアイコンが表示されている。

**Comment by unomitsu** [comment]
### 確認内容 1
htmlの要素からアイコンのイメージのsrcを確認。
srcのurlをデコードをしたURLを開く。

- アイコンのイメージのsrc
> \<img src="/_next/image?url=https%3A%2F%2Favatars3.githubusercontent.com%2Fu%2F45159438%3Fv%3D4&amp;w=384&amp;q=75" alt="unomitsu" class="rounded-full" width="120" height="120"\>

- デコード後のURL
> https://avatars3.githubusercontent.com/u/45159438?v=4&amp;w=384&amp;q=75


### 確認結果
デコードしたURLを開くと、正しいアイコンの画像が開けた。

**Comment by unomitsu** [comment]
### 確認内容 2

右クリックから、新しいタブで画像を開くをすると、以下のエラー文が出る。

> 400: BAD_REQUEST
Code: INVALID_IMAGE_OPTIMIZE_REQUEST
ID: hnd1::pw2n8-1608606009046-7542fee433e8

**Comment by yamakenji24** [comment]
## 理由
アイコンが表示されない理由として、対応するドメインを設定ファイルに記述していないためだと考えられる。
事実、手元上で確認したところ、ドメインの対応がされていなかった

## 対応策
現状、対応策として二つ考えている。

まず一つ目として、対応するドメインを列挙すること。現状、next/imageのドメインを設定する際に、サブドメインをワイルドカードで設定することができない。そのため、列挙する必要がある。ただし、対応するサブドメインがどれほどあるのか不明なため、現実的でない

2つ目としては、next/imageの最適化の利用を見送る。1つ目の対応策が事実上現実的でないため、この策が好ましいと考えている。
